"""
Django settings for scoring project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

from django.conf import settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j%8^184^y%$=1w!z!_@h%t1d!x56!y=15z!^_5z!_5z!_5z!_5z!_5z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'management',
    'notebook',
    'qd',
    'exam.apps.ExamConfig',
    'rest_framework_simplejwt',
    'teacher_topic.apps.TeacherTopicConfig',
    "Notification.apps.NotificationConfig",
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ]
}
MIDDLEWARE = [

    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

from datetime import timedelta

SIMPLE_JWT = {
    # Access Token 有效期（默认 5 分钟，建议设为 1-2 小时）
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    # Refresh Token 有效期（默认 1 天，建议设为 7 天）
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # Token 加密算法（默认 HS256）
    'ALGORITHM': 'HS256',
    # 签名密钥（默认使用 Django 的 SECRET_KEY，生产环境建议单独设置）
    'SIGNING_KEY': settings.SECRET_KEY,
    # 是否验证 Token 有效期（默认 True）
    'VERIFYING_KEY': None,
}

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",  # 允许 Authorization 头（关键！）
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]


ROOT_URLCONF = 'scoring.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scoring.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'questiondatabase',
            'USER': 'root',
            'PASSWORD': '123456',
            'HOST': 'localhost',
            'PORT': '3310',
        },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
CORS_ORIGIN_ALLOW_ALL = True
AUTH_USER_MODEL = 'management.User'



# 邮箱地址配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' #使用smtp作为发送邮件的后端
EMAIL_HOST = 'smtp.qq.com' #smtp服务器地址
EMAIL_HOST_USER = '794926067@qq.com' #发送邮件的邮箱账号
EMAIL_HOST_PASSWORD = 'tbhiftjkycfdbccf' #授权码
EMAIL_PORT = 587 #smtp端口号
EMAIL_USE_TLS = True#实现加密通信
DEFAULT_FROM_EMAIL = '794926067@qq.com'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CORS_ALLOW_CREDENTIALS = True

# 为测试环境允许所有来源（生产环境应移除）
CORS_ALLOW_ALL_ORIGINS = True


# QuickAuth 配置
QUICKAUTH_APPID='89ed8d8e'
QUICKAUTH_APPSECRET='d16015151e1bb1e3ceb941d7aa7ff77d'
QUICKAUTH_REDIRECT_URI= 'http://127.0.0.1:8000/quickauth/callback/' # 需与平台实际接口一致
QUICKAUTH_AUTH_URL='http://api.qauth.cn/oauth' # 需与平台实际接口一致
QUICKAUTH_TOKEN_URL='http://api.qauth.cn/oauth/access_token'  # 需与平台实际接口一致
QUICKAUTH_USERINFO_URL='http://api.qauth.cn/oauth/userinfo'


TONGYI_API_KEY = 'sk-8115c1fed2d349a791f9a1572627740f'










