# Generated by Django 5.2.6 on 2025-09-23

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import NotificationViewSet
from . import views_batch

# 创建 router 实例
router = DefaultRouter()

# 注册通知视图集
router.register(r"notifications", NotificationViewSet, basename="notification")

app_name = "notification"
urlpatterns = [
    path("", include(router.urls)),  # 将 router 的路由包含进来
    path("batch-mark-as-read/", views_batch.mark_notifications_as_read, name="batch_mark_as_read"),  # 批量标记已读
]