# Generated by Django 5.2.5 on 2026-05-19 07:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.IntegerField()),
                ('question_number', models.IntegerField()),
                ('answer', models.TextField()),
                ('score', models.FloatField()),
                ('true_false', models.BooleanField()),
                ('type1', models.CharField(max_length=110, verbose_name='题目类型')),
            ],
            options={
                'db_table': 'answer_detail',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('specialty', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'class_name',
            },
        ),
        migrations.CreateModel(
            name='ExamRecordEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField()),
                ('exam_paper_number', models.IntegerField()),
            ],
            options={
                'db_table': 'exam_record',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade10', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('topic_number', models.IntegerField()),
            ],
            options={
                'db_table': 'questiondatebase_topic',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('specialty10', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'specialty',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=20)),
                ('choice_count', models.IntegerField(default=0)),
                ('choice_score', models.FloatField(default=0)),
                ('multiple_choice_count', models.IntegerField(default=0)),
                ('multiple_choice_score', models.FloatField(default=0)),
                ('calculation_analysis_count', models.IntegerField(default=0)),
                ('calculation_analysis_score', models.FloatField(default=0)),
                ('case_analysis_count', models.IntegerField(default=0)),
                ('case_analysis_score', models.FloatField(default=0)),
                ('comprehensive_count', models.IntegerField(default=0)),
                ('comprehensive_score', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='TopicExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_number', models.IntegerField()),
                ('examPaper_number', models.IntegerField()),
            ],
            options={
                'db_table': 'topic_exam',
            },
        ),
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('description', models.TextField(blank=True, verbose_name='标签描述')),
            ],
            options={
                'db_table': 'topic_tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(default='student', max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('class1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='management.class')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='class1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classname', to='management.classname'),
        ),
        migrations.CreateModel(
            name='ContactRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_time', models.DateTimeField()),
                ('topic_number', models.IntegerField()),
                ('topic_knowledge', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact_record',
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('all_score', models.IntegerField()),
                ('status', models.BooleanField()),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_person', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_exam', to='management.subject')),
            ],
            options={
                'db_table': 'exam_paper',
            },
        ),
        migrations.CreateModel(
            name='ExamParticipation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('submitted', '已交卷'), ('graded', '已评分')], default='not_started', max_length=20)),
                ('all_score', models.FloatField(blank=True, null=True, verbose_name='总分')),
                ('obtained_score', models.FloatField(blank=True, null=True, verbose_name='获得分数')),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='management.exampaper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_participation',
                'unique_together': {('exam_paper', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('begin_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('end_time', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('end_score', models.FloatField()),
                ('exam_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='management.exampaper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_record_ex',
            },
        ),
        migrations.CreateModel(
            name='ExamSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('passing_score', models.FloatField(verbose_name='及格线')),
                ('duration', models.IntegerField(verbose_name='考试时长(分钟)')),
                ('begin_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('draw_rule', models.CharField(choices=[('manual', '手动选题'), ('random', '随机抽题')], max_length=20)),
                ('difficulty_distribution', models.JSONField(blank=True, null=True, verbose_name='难度分布')),
                ('knowledge_distribution', models.JSONField(blank=True, null=True, verbose_name='知识点分布')),
                ('exam_paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='management.exampaper')),
            ],
            options={
                'db_table': 'exam_setting',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='grade1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='management.grade'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('考试通知', '考试通知'), ('成绩通知', '成绩通知'), ('题目审核通知', '题目审核通知'), ('系统公告通知', '系统公告通知'), ('错题本更新通知', '错题本更新通知'), ('学习计划推荐通知', '学习计划推荐通知')], default='系统公告通知', max_length=50)),
                ('notification_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='ExamNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_exam_notification', models.BooleanField(default=True)),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='management.exampaper')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_detail', to='management.notification')),
            ],
            options={
                'db_table': 'exam_notification',
            },
        ),
        migrations.CreateModel(
            name='OperationRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('operation_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_operation_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operation_record',
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_record_time', models.DateTimeField()),
                ('topic_number', models.TextField()),
                ('review_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='ScoreReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('statistics', models.JSONField(verbose_name='成绩统计信息')),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_report', to='management.examparticipation')),
            ],
            options={
                'db_table': 'score_report',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='specialty1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialty', to='management.specialty'),
        ),
        migrations.CreateModel(
            name='QuestionDatabase',
            fields=[
                ('Question_number', models.AutoField(primary_key=True, serialize=False)),
                ('question_total', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
                ('question_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('if_public', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade1', to='management.grade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject1', to='management.subject')),
            ],
            options={
                'db_table': 'question_database',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_number', models.AutoField(primary_key=True, serialize=False)),
                ('topic_content', models.TextField()),
                ('topic_answer', models.TextField()),
                ('A', models.CharField(blank=True, max_length=20, null=True)),
                ('B', models.CharField(blank=True, max_length=20, null=True)),
                ('C', models.CharField(blank=True, max_length=20, null=True)),
                ('D', models.CharField(blank=True, max_length=20, null=True)),
                ('E', models.CharField(blank=True, max_length=20, null=True)),
                ('topic_difficulty', models.CharField(max_length=20)),
                ('score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic_knowledge', models.TextField()),
                ('topic_type', models.CharField(blank=True, max_length=110, null=True, verbose_name='题目类型')),
                ('topic_analysis', models.TextField()),
                ('Q_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Q_data', to='management.questiondatabase')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='AutoScoringRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(verbose_name='题目分数')),
                ('answer', models.TextField(verbose_name='标准答案')),
                ('grading_method', models.CharField(choices=[('automatic', '自动评分'), ('manual', '人工评分')], default='automatic', max_length=20)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rule', to='management.topic')),
            ],
            options={
                'db_table': 'auto_scoring_rule',
            },
        ),
        migrations.CreateModel(
            name='WrongTopic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_number', models.IntegerField()),
                ('error_times', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField()),
                ('topic_knowledge', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wrong', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wrong_topic',
            },
        ),
        migrations.CreateModel(
            name='ExamProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(blank=True, null=True, verbose_name='考生答案')),
                ('is_answered', models.BooleanField(default=False)),
                ('is_marked', models.BooleanField(default=False, verbose_name='是否标记')),
                ('saved_at', models.DateTimeField(auto_now=True, verbose_name='保存时间')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='management.examparticipation')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_progress', to='management.topic')),
            ],
            options={
                'db_table': 'exam_progress',
                'unique_together': {('participation', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='TopicTagRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='management.topictag')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='management.topic')),
            ],
            options={
                'db_table': 'topic_tag_relation',
                'unique_together': {('topic', 'tag')},
            },
        ),
    ]
