# Generated by Django 5.2.5 on 2026-05-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='judgment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='judgment_score',
            field=models.FloatField(default=0),
        ),
    ]
