# Generated by Django 5.2.5 on 2026-05-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_subject_judgment_count_subject_judgment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_knowledge',
            field=models.TextField(blank=True, null=True),
        ),
    ]
