# Generated by Django 5.2.5 on 2026-05-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_topic_topic_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='A',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='B',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='C',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='D',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='E',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
